

/* Insert Cart Product Details */
/*INSERT INTO CART_PRODUCT_MAPPING VALUES (1, 1, 2, 1, 'Y', 1, NOW(), 1, NOW(), 0);
INSERT INTO CART_PRODUCT_MAPPING VALUES (2, 1, 6, 1, 'Y', 1, NOW(), 1, NOW(), 0);
INSERT INTO CART_PRODUCT_MAPPING VALUES (3, 1, 11, 2, 'Y', 1, NOW(), 1, NOW(), 0);

INSERT INTO CART_PRODUCT_MAPPING VALUES (4, 2, 10, 4, 'Y', 1, NOW(), 1, NOW(), 0);
*/