DROP TABLE IF EXISTS CART_DETAILS;
CREATE TABLE CART_DETAILS(
	CART_ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT(10) NOT NULL UNIQUE,
	IS_ACTIVE CHAR NOT NULL,
	CREATED_BY INT(10) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_BY INT(10),
	LAST_MODIFIED_DATE TIMESTAMP,
	VERSION INT(10) NOT NULL
);

DROP TABLE IF EXISTS CART_PRODUCT_MAPPING;
CREATE TABLE CART_PRODUCT_MAPPING(
	CART_PRODUCT_ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CART_ID INT(10) NOT NULL,
	PRODUCT_ID INT(10) NOT NULL,
	PRODUCT_COUNT INT(10) NOT NULL,
	IS_ACTIVE CHAR NOT NULL,
	CREATED_BY INT(10) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_BY INT(10),
	LAST_MODIFIED_DATE TIMESTAMP,
	VERSION INT(10) NOT NULL
);