DROP TABLE IF EXISTS PAYMENT_DETAILS;
CREATE TABLE PAYMENT_DETAILS(
	PAYMENT_ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT(10) NOT NULL,
	PAYMENT_REQUEST_ID INT(16) NOT NULL,
	TRANSACTION_ID VARCHAR(20) NOT NULL,
	PAYMENT_AMOUNT DECIMAL(10,2) NOT NULL,
	PAYMENT_DATE TIMESTAMP NOT NULL,
	BANK_STATUS VARCHAR(20) NOT NULL,
	PAYMENT_STATUS VARCHAR(20) NOT NULL,
	CARD_ID INT(10) NOT NULL,
	IS_ACTIVE CHAR NOT NULL,
	CREATED_BY INT(10) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_BY INT(10),
	LAST_MODIFIED_DATE TIMESTAMP,
	VERSION INT(10) NOT NULL
);

DROP TABLE IF EXISTS CARD_DETAILS;
CREATE TABLE CARD_DETAILS(
	CARD_ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PAYEE_NAME VARCHAR(50) NOT NULL,
	CARD_NUMBER INT(20) NOT NULL,
	CARD_TYPE_ID INT(10) NOT NULL,
	CARD_NAME_ID INT(10) NOT NULL,
	VALIDITY_DATE TIMESTAMP NOT NULL,
	IS_ACTIVE CHAR NOT NULL,
	CREATED_BY INT(10) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_BY INT(10),
	LAST_MODIFIED_DATE TIMESTAMP,
	VERSION INT(10) NOT NULL
);

DROP TABLE IF EXISTS CARD_TYPE_DETAILS;
CREATE TABLE CARD_TYPE_DETAILS(
	CARD_TYPE_ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CARD_TYPE_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE CHAR NOT NULL,
	CREATED_BY INT(10) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_BY INT(10),
	LAST_MODIFIED_DATE TIMESTAMP,
	VERSION INT(10) NOT NULL
);

DROP TABLE IF EXISTS CARD_NAME_DETAILS;
CREATE TABLE CARD_NAME_DETAILS(
	CARD_NAME_ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CARD_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE CHAR NOT NULL,
	CREATED_BY INT(10) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_BY INT(10),
	LAST_MODIFIED_DATE TIMESTAMP,
	VERSION INT(10) NOT NULL
);
